use super::instruction::{Instruction, InstructionCycle::*};

macro_rules! instruction_table {
    ($($_: literal: $identifier: expr, $($cycles: expr)=>*);+) => {
        &[
            $(Instruction {identifier: $identifier, cycles: &[$($cycles,)*]},)*
        ]
    };
}

// fetch is not listed as a cycle step as it needs to be handled separately for the pipeline
pub const INSTRUCTIONS: &[Instruction] = instruction_table!(
    0x00: "NYI", NYI;
    0x01: "NYI", NYI;
    0x02: "NYI", NYI;
    0x03: "NYI", NYI;
    0x04: "NYI", NYI;
    0x05: "NYI", NYI;
    0x06: "NYI", NYI;
    0x07: "NYI", NYI;
    0x08: "PHP", Read=>Php;
    0x09: "NYI", NYI;
    0x0A: "NYI", NYI;
    0x0B: "NYI", NYI;
    0x0C: "NYI", NYI;
    0x0D: "NYI", NYI;
    0x0E: "NYI", NYI;
    0x0F: "NYI", NYI;
    0x10: "BPL rel", RelOperand=>Bpl=>RelBranch1=>RelBranch2;
    0x11: "NYI", NYI;
    0x12: "NYI", NYI;
    0x13: "NYI", NYI;
    0x14: "NYI", NYI;
    0x15: "NYI", NYI;
    0x16: "NYI", NYI;
    0x17: "NYI", NYI;
    0x18: "CLC impl", Read=>Clc;
    0x19: "NYI", NYI;
    0x1A: "NYI", NYI;
    0x1B: "NYI", NYI;
    0x1C: "NYI", NYI;
    0x1D: "NYI", NYI;
    0x1E: "NYI", NYI;
    0x1F: "NYI", NYI;
    0x20: "JSR abs", Jsr1=>Jsr2=>Jsr3=>Jsr4=>Jsr5=>Jsr6;
    0x21: "NYI", NYI;
    0x22: "NYI", NYI;
    0x23: "NYI", NYI;
    0x24: "NYI", NYI;
    0x25: "NYI", NYI;
    0x26: "NYI", NYI;
    0x27: "NYI", NYI;
    0x28: "PLP", Read=>ReadStack=>PopStack=>Plp;
    0x29: "NYI", NYI;
    0x2A: "NYI", NYI;
    0x2B: "NYI", NYI;
    0x2C: "NYI", NYI;
    0x2D: "NYI", NYI;
    0x2E: "NYI", NYI;
    0x2F: "NYI", NYI;
    0x30: "BMI rel", RelOperand=>Bmi=>RelBranch1=>RelBranch2;
    0x31: "NYI", NYI;
    0x32: "NYI", NYI;
    0x33: "NYI", NYI;
    0x34: "NYI", NYI;
    0x35: "NYI", NYI;
    0x36: "NYI", NYI;
    0x37: "NYI", NYI;
    0x38: "SEC impl", Read=>Sec;
    0x39: "NYI", NYI;
    0x3A: "NYI", NYI;
    0x3B: "NYI", NYI;
    0x3C: "NYI", NYI;
    0x3D: "NYI", NYI;
    0x3E: "NYI", NYI;
    0x3F: "NYI", NYI;
    0x40: "NYI", NYI;
    0x41: "NYI", NYI;
    0x42: "NYI", NYI;
    0x43: "NYI", NYI;
    0x44: "NYI", NYI;
    0x45: "NYI", NYI;
    0x46: "NYI", NYI;
    0x47: "NYI", NYI;
    0x48: "PHA impl", Read=>Pha;
    0x49: "NYI", NYI;
    0x4A: "NYI", NYI;
    0x4B: "NYI", NYI;
    0x4C: "JMP abs", AbsOperand1=>AbsOperand2=>JmpAbs;
    0x4D: "NYI", NYI;
    0x4E: "NYI", NYI;
    0x4F: "NYI", NYI;
    0x50: "BVC rel", RelOperand=>Bvc=>RelBranch1=>RelBranch2;
    0x51: "NYI", NYI;
    0x52: "NYI", NYI;
    0x53: "NYI", NYI;
    0x54: "NYI", NYI;
    0x55: "NYI", NYI;
    0x56: "NYI", NYI;
    0x57: "NYI", NYI;
    0x58: "CLI impl", Read=>Cli;
    0x59: "NYI", NYI;
    0x5A: "NYI", NYI;
    0x5B: "NYI", NYI;
    0x5C: "NYI", NYI;
    0x5D: "NYI", NYI;
    0x5E: "NYI", NYI;
    0x5F: "NYI", NYI;
    0x60: "RTS impl", ReadInc=>Rts1=>Rts2=>Rts3=>Rts4=>Read;
    0x61: "ADC (ind,x)", ZpgOperand=>ZpgIndexedOperand=>IndirectXAddressLo=>IndirectIndexedAddressHi=>AbsOperand3=>Adc1;
    0x62: "NYI", NYI;
    0x63: "NYI", NYI;
    0x64: "NYI", NYI;
    0x65: "NYI", NYI;
    0x66: "NYI", NYI;
    0x67: "NYI", NYI;
    0x68: "PLA impl", Read=>ReadStack=>PopStack=>Pla;
    0x69: "ADC imm", ImmOperand=>Adc1;
    0x6A: "NYI", NYI;
    0x6B: "NYI", NYI;
    0x6C: "NYI", NYI;
    0x6D: "ADC abs", AbsOperand1=>AbsOperand2=>AbsOperand3=>Adc1;
    0x6E: "NYI", NYI;
    0x6F: "NYI", NYI;
    0x70: "BVS rel", RelOperand=>Bvs=>RelBranch1=>RelBranch2;
    0x71: "ADC (ind),y", ZpgOperand=>IndirectYAddressLo=>IndirectIndexedAddressHi=>AbsYOperand=>AbsIndexedPageCross=>Adc1;
    0x72: "NYI", NYI;
    0x73: "NYI", NYI;
    0x74: "NYI", NYI;
    0x75: "ADC zpg,x", ZpgOperand=>ZpgIndexedOperand=>ZpgXOperand=>Adc1;
    0x76: "NYI", NYI;
    0x77: "NYI", NYI;
    0x78: "SEI impl", Read=>Sei;
    0x79: "ADC abs,y", AbsOperand1=>AbsOperand2=>AbsYOperand=>AbsIndexedPageCross=>Adc1;
    0x7A: "NYI", NYI;
    0x7B: "NYI", NYI;
    0x7C: "NYI", NYI;
    0x7D: "ADC abs,x", AbsOperand1=>AbsOperand2=>AbsXOperand=>AbsIndexedPageCross=>Adc1;
    0x7E: "NYI", NYI;
    0x7F: "NYI", NYI;
    0x80: "NYI", NYI;
    0x81: "NYI", NYI;
    0x82: "NYI", NYI;
    0x83: "NYI", NYI;
    0x84: "NYI", NYI;
    0x85: "NYI", NYI;
    0x86: "NYI", NYI;
    0x87: "NYI", NYI;
    0x88: "DEY impl", Read=>Dey2;
    0x89: "NYI", NYI;
    0x8A: "TXA impl", Read=>Txa;
    0x8B: "NYI", NYI;
    0x8C: "NYI", NYI;
    0x8D: "NYI", NYI;
    0x8E: "NYI", NYI;
    0x8F: "NYI", NYI;
    0x90: "BCC rel", RelOperand=>Bcc=>RelBranch1=>RelBranch2;
    0x91: "NYI", NYI;
    0x92: "NYI", NYI;
    0x93: "NYI", NYI;
    0x94: "NYI", NYI;
    0x95: "NYI", NYI;
    0x96: "NYI", NYI;
    0x97: "NYI", NYI;
    0x98: "TYA impl", Read=>Tya;
    0x99: "NYI", NYI;
    0x9A: "TXS impl", Read=>Txs;
    0x9B: "NYI", NYI;
    0x9C: "NYI", NYI;
    0x9D: "NYI", NYI;
    0x9E: "NYI", NYI;
    0x9F: "NYI", NYI;
    0xA0: "LDY imm", ImmOperand=>Ldy;
    0xA1: "NYI", NYI;
    0xA2: "LDX imm", ImmOperand=>Ldx;
    0xA3: "NYI", NYI;
    0xA4: "NYI", NYI;
    0xA5: "NYI", NYI;
    0xA6: "NYI", NYI;
    0xA7: "NYI", NYI;
    0xA8: "TAY impl", Read=>Tay;
    0xA9: "LDA imm", ImmOperand=>Lda;
    0xAA: "TAX impl", Read=>Tax;
    0xAB: "NYI", NYI;
    0xAC: "NYI", NYI;
    0xAD: "NYI", NYI;
    0xAE: "NYI", NYI;
    0xAF: "NYI", NYI;
    0xB0: "BCS rel", RelOperand=>Bcs=>RelBranch1=>RelBranch2;
    0xB1: "NYI", NYI;
    0xB2: "NYI", NYI;
    0xB3: "NYI", NYI;
    0xB4: "NYI", NYI;
    0xB5: "NYI", NYI;
    0xB6: "NYI", NYI;
    0xB7: "NYI", NYI;
    0xB8: "CLV impl", Read=>Clv;
    0xB9: "NYI", NYI;
    0xBA: "TSX impl", Read=>Tsx;
    0xBB: "NYI", NYI;
    0xBC: "NYI", NYI;
    0xBD: "NYI", NYI;
    0xBE: "NYI", NYI;
    0xBF: "NYI", NYI;
    0xC0: "NYI", NYI;
    0xC1: "NYI", NYI;
    0xC2: "NYI", NYI;
    0xC3: "NYI", NYI;
    0xC4: "NYI", NYI;
    0xC5: "NYI", NYI;
    0xC6: "NYI", NYI;
    0xC7: "NYI", NYI;
    0xC8: "NYI", NYI;
    0xC9: "NYI", NYI;
    0xCA: "NYI", NYI;
    0xCB: "NYI", NYI;
    0xCC: "NYI", NYI;
    0xCD: "NYI", NYI;
    0xCE: "NYI", NYI;
    0xCF: "NYI", NYI;
    0xD0: "BNE rel", RelOperand=>Bne=>RelBranch1=>RelBranch2;
    0xD1: "NYI", NYI;
    0xD2: "NYI", NYI;
    0xD3: "NYI", NYI;
    0xD4: "NYI", NYI;
    0xD5: "NYI", NYI;
    0xD6: "NYI", NYI;
    0xD7: "NYI", NYI;
    0xD8: "CLD", Read=>Cld;
    0xD9: "NYI", NYI;
    0xDA: "NYI", NYI;
    0xDB: "NYI", NYI;
    0xDC: "NYI", NYI;
    0xDD: "NYI", NYI;
    0xDE: "NYI", NYI;
    0xDF: "NYI", NYI;
    0xE0: "NYI", NYI;
    0xE1: "NYI", NYI;
    0xE2: "NYI", NYI;
    0xE3: "NYI", NYI;
    0xE4: "NYI", NYI;
    0xE5: "NYI", NYI;
    0xE6: "INC zpg", ZpgOperand=>Inc2=>Inc3=>Inc4;
    0xE7: "NYI", NYI;
    0xE8: "INX impl", Read=>Inx2;
    0xE9: "NYI", NYI;
    0xEA: "NYI", NYI;
    0xEB: "NYI", NYI;
    0xEC: "NYI", NYI;
    0xED: "NYI", NYI;
    0xEE: "NYI", NYI;
    0xEF: "NYI", NYI;
    0xF0: "BEQ rel", RelOperand=>Beq=>RelBranch1=>RelBranch2;
    0xF1: "NYI", NYI;
    0xF2: "NYI", NYI;
    0xF3: "NYI", NYI;
    0xF4: "NYI", NYI;
    0xF5: "NYI", NYI;
    0xF6: "NYI", NYI;
    0xF7: "NYI", NYI;
    0xF8: "SED impl", Read=>Sed;
    0xF9: "NYI", NYI;
    0xFA: "NYI", NYI;
    0xFB: "NYI", NYI;
    0xFC: "NYI", NYI;
    0xFD: "NYI", NYI;
    0xFE: "NYI", NYI;
    0xFF: "NYI", NYI
);
