[package]
name = "jade-validate"
version = "0.1.0"
edition = "2021"

[dependencies]
jade = { path = "../jade" }
thiserror = "2.0.11"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.14"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
